"""Holds the POS object, just to get it out of the main script"""

# Parts of speech dict with various information about each, used in processing questions
POS = {
         'AP' : {'name'    : 'determiner/pronoun, post-determiner',
                 'lexnames': [],
                 'ref'     : False,
                },
         'NN' : {'name'    : 'noun',
                 'lexnames': [
                                'noun.animal',
                                'noun.artifact',
                                'noun.body',
                                'noun.food',
                                'noun.motive',
                                'noun.plant',
                                'noun.shape',
                             ],
                 'ref'     : True,
                },
         'NN$': {'name'    : 'noun, singular, common, genitive',
                 'lexnames': [
                                'noun.animal',
                                'noun.artifact',
                                'noun.body',
                                'noun.food',
                                'noun.motive',
                                'noun.plant',
                                'noun.shape',
                             ],
                 'ref'     : True,
                },
         'NNS': {'name'    : 'noun, plural, common',
                 'lexnames': [
                                'noun.animal',
                                'noun.artifact',
                                'noun.body',
                                'noun.food',
                                'noun.motive',
                                'noun.plant',
                                'noun.shape',
                             ],
                 'ref'     : False,
                },
         'PN' : {'name'    : 'pronoun',
                 'lexnames': [],
                 'ref'     : False,
                },
         'VB' : {'name'    : 'verb',
                 'lexnames': [
                                'verb.body',
                                'verb.competition',
                                'verb.contact',
                                'verb.perception',
                                'verb.possession',
                                'verb.social',
                             ],
                 'ref'     : False,
                },
         'VBG': {'name'    : 'verb, present participle or gerund',
                 'lexnames': [
                                'verb.body',
                                'verb.competition',
                                'verb.contact',
                                'verb.perception',
                                'verb.possession',
                                'verb.social',
                             ],
                 'ref'     : False,
                },
         'VBN': {'name'    : 'past-participle',
                 'lexnames': [],
                 'ref'     : False,
                },
         'VBZ': {'name'    : 'verb, present tense, 3rd person singular',
                 'lexnames': [
                                'verb.body',
                                'verb.competition',
                                'verb.contact',
                                'verb.perception',
                                'verb.possession',
                                'verb.social',
                             ],
                 'ref'     : False,
                },
      }
